### ISSUE TITLE
Simplify catalogue config files

### ISSUE THREAD

**Issue by nichtich** [pkiraly/qa-catalogue#260]
Having two different methods to execute analysis (`catalogue/$NAME.sh` and `metadata-qa.sh`) makes difficult to change the process. I'd like to remove [support of] `metadata-qa.sh` so the configuration of catalogues can be simplified, e.g. by removal of explictly setting `NAME` as it is automatically set from script name (I've checked via `cd catalogues; grep NAME= *.sh | egrep -v '^([^.]+)\.sh:NAME=\1'`).

By now the script `metadata-qa.sh` is documented in README.md but not referenced elsewhere in the code base.

**Comment by pkiraly** [comment]
`metadata-qa.sh` is a kind of fallback script which could be used if not `catalogue/$NAME` scripts is available, i.e. it is handy if as a newcommer you would like to try QA catalogue. It is particularly handy in a Docker environment. You can think of a general entry, while the catalogue scripts are customized entries. Once you test the system with it, you can store your variables into a fix script.

**Comment by nichtich** [comment]
Ok, I only wonder about [this lines](https://github.com/pkiraly/metadata-qa-marc/blob/main/metadata-qa.sh#L31-L41).

Configuration in general could be simplified by reducing the number of  configuration places. So far I found:

1. backend file `setdir.sh`
2.
   a) backend parameters of `metadata-qa.sh` (`--name`, `--params`, `--mask`...)
   b) backend file `catalogues/$NAME.sh`
3. frontend file `configuration.cfg`
4. frontend class  `classes/catalogue/$NAME.php`

In addition there are `*.params.json` files in the output directory to pass configuration from backend to frontend. It works the way it is but I'd keep this issue open for discussion.

**Comment by pkiraly** [comment]
a short comment: `*.params.json` files are created during the analysis, and they contain the actual parameters for the analysis.

**Comment by nichtich** [comment]
`metadata-qa.sh` should neither require `setdir.sh` nor [modify hard-coded path files](https://github.com/pkiraly/qa-catalogue/blob/main/metadata-qa.sh#L47) but get all values from environment files or command line arguments.

**Comment by nichtich** [comment]
I've extened `metadata-qa.sh` to only load `setdir.sh` if this file exists, so `metadata-qa.sh` can be used as primary entry point without any configuration files. Only [these lines](https://github.com/pkiraly/qa-catalogue/blob/main/metadata-qa.sh#L64-L91) puzzle me:

- There is no need to always print the configuration because it is already printed in `common-script`, so we get it twice.
- The variable `CATALOGUE` seems to serve multiple purposes and this use looks like a dirty misplaced hack. Better put the login into another script and call these script independently

**Comment by nichtich** [comment]
I've fixed the status code of grep. However the whole section about changing `/var/www/html/qa-catalogue/configuration.cnf` should be (re)moved as it is a hack only relevant to your installation setup. Can you explain the rationale behind it? There should be a better and more generalized way.

**Comment by pkiraly** [comment]
This script was created for being an entry pint for running analyses in Docker. The Dockerfile describes the fixed structure of the frontend and backend. The important part here is the CATALOGUE variable which should be write into the web frontend's configuration file, in order to fetch the catalogue related class.

**Comment by nichtich** [comment]
I'd like to use the script (now `qa-catalogue`) as primary executable to run the analysis. I can imagine two ways to remove the hard-coded path:

- create another script, e.g. `update-catalogue-name.sh` and run this script before or after `qa-catalogue` (or run `qa-catalogue` from within this script)
- add a parameter, e.g, `--w --web-config` to optionally point to the web configuration to get updated

**Comment by pkiraly** [comment]
I go for the second option. Maybe later we can split it. The reason: I would like to keep the analysis process runable with a single command. It would also be possible to create a 3 script: `qa-catalogue` (for running the analysis), `update-catalogue-name.sh` (update web config) and a light one which calls these two, and used only in Docker (`qa-catalogue.docker.sh`?)

**Comment by nichtich** [comment]
As far as I can see, qa-catalogue can fully be used by directly calling `qa-catalogue`. The scripts in `catalogues/` could be modified to call `qa-catalogue` instead of rather internal `common-script` but this seems to be more cleanup with low priority. Closing this issue for this reason.
