### ISSUE TITLE
Analysis parameter files should be written at the end of analysis

### ISSUE THREAD

**Issue by nichtich** [pkiraly/qa-catalogue#343]
It looks like analysis parameter files such as `completeness.params.json` are written at the start of analysis (via `processor.beforeIteration`) . This results in start time shown via `analysisTimestamp` in the client when the end time of analysis should be shown instead.

**Comment by pkiraly** [comment]
It is testable. It is enough to run on a smaller dataset (e.g. 100K records). It takes minutes, not 2 days.

**Comment by nichtich** [comment]
The visible timestamp in the client helps to tell whether/when the analysis has been finished. Current setup with 73 million PICA records took 2 to 2:30 hours for each of completeness, classifications, and authorities.

**Comment by pkiraly** [comment]
Sorry, I do not understand this comment. The client = the web UI? In the web UI there is a visible timestamp. What is missing is an explicit "status" information, such as `started at <date time>` or `finished at <date time>`. We can also add the duration of the process, such as `finished at <date time> took <duration>`.
When I mentioned that it takes minutes (if you run the tool on 100K records) I mean everything including index. Completeness etc. take some hours, but the indexing takes much longer.
