### ISSUE TITLE
Write number of processed records to parameters File

### ISSUE THREAD

**Issue by nichtich** [pkiraly/qa-catalogue#344]
The parameters file, written in `afterIteration` of each task should include the `numberOfprocessedRecords` to store the actual number of processed records. By now only validation task stores this number, but in `count.csv`. Putting the number in parameters file will allow to show the actual number for each task in qa-catalogue-web. This is required because some analysis are performed more regularly then others at VZG.

**Comment by pkiraly** [comment]
It is testable
