### ISSUE TITLE
Debian or Flatpak package for Linux

### ISSUE THREAD

**Issue by pabloab** [pkiraly/qa-catalogue#355]
Would be great to offer/build Linux installer on a Flatpak package. Afterward could be [offered on Flathub](https://github.com/flathub/flathub/wiki/App-Submission), so the installation process end up being just `flatpak install flathub qa-catalogue ` (`flatpak install qa-catalogue ` will probably work too).

Offering a `.deb` would be nice too.

**Comment by pkiraly** [comment]
@pabloab Thanks for the idea. Could you recommend a tutorial how to create a `.deb` package? I am not familiar with Flatpak, so a tutorial for that would be useful as well.

**Comment by pabloab** [comment]
Considering all those CLI commands, and the fact that Flatpak is sadly heavily [GUI-oriented](https://docs.flatpak.org/en/latest/introduction.html#target-audience), maybe this issue should be reoriented to deb package.

I'm far from an expert, but [this](https://wiki.debian.org/Packaging) seems like a good starting point. Possibly even better [this java-oriented](https://wiki.debian.org/Java/Packaging) guide.

**Comment by pkiraly** [comment]
Thanks a lot!

**Comment by nichtich** [comment]
We are working on better support of Docker images so decided against providing yet another package form because this requires maintainance.
