### ISSUE TITLE
Enable to import both Avram and "Yale" format of schema files

### ISSUE THREAD

**Issue by pkiraly** [pkiraly/qa-catalogue#373]
This is needed for the inclusion of #371.

**Comment by nichtich** [comment]
No need to do so, as the Yale format is being changed to comply to Avram specification.

**Comment by nichtich** [comment]
Is class `YaleMarc21SchemaReader` still used? As far as I understand, both the class and `src/main/resources/marc/authority-schema.yale.json` are only used in test class `YaleMarc21SchemaReaderTest` but not on production, so they can be removed?

**Comment by pkiraly** [comment]
The analysis based on the authority schema is not yet in production, but only used in test classes (following a test driven development version). I think you are right, the YaleMarc21SchemaReader could be removed shortly.
