### ISSUE TITLE
Docker example does not work

### ISSUE THREAD

**Issue by MontyBitto** [pkiraly/qa-catalogue#417]
In step 2 no file or directory ./qa-catalogue exists.

**Comment by pkiraly** [comment]
Dear @MontyBitto 
Could you paste the exact command (both step 1 and 2) and the error message here? Otherwise it is very hard to debug. One more question: in which operating system did you run it?

**Comment by pkiraly** [comment]
@MontyBitto 
Sorry, I found that there is an issue in the README file. The document mixes 0.6.0 and 0.7.0. In the 0.6.0 the main script was called `metadata-qa.sh`, while in 0.7.0 it was renamed to `qa-catalogue`.

```
# stop and remove the current docker container
docker container stop metadata-qa-marc
docker container rm metadata-qa-marc

# set the directory where you store the bibliographic records
BIBL_RECORD_DIRECTORY=<add your input dir>

# initialize the docker container
docker run \
  -d \
  -v $BIBL_RECORD_DIRECTORY:/opt/qa-catalogue/marc \
  -p 8983:8983 -p 80:80 \
  --name metadata-qa-marc \
  pkiraly/metadata-qa-marc:0.7.0

# run the analyses (in this example these parameters are for Gent university catalogue)
docker container exec \
  -ti \
  metadata-qa-marc-v0.7 \
  ./qa-catalogue \
  --params "--marcVersion GENT --alephseq" \
  --mask "rug01.backup.2024-02-10.gz" \
  --catalogue gent \
  all
```

**Comment by pkiraly** [comment]
Dear @MontyBitto have you had a chance to test if it works for you?

**Comment by MontyBitto** [comment]
Yes, it worked now. Thank you.

**Comment by pkiraly** [comment]
Many thanks for the feedback!
