### ISSUE TITLE
Build and publish docker image via GitHub action

### ISSUE THREAD

**Issue by nichtich** [pkiraly/qa-catalogue#435]
As described at https://docs.github.com/en/actions/publishing-packages/publishing-docker-images - I'd use GitHub packages instead of Docker hub to only have one place.

**Comment by pkiraly** [comment]
I have implemented it. There is a new `.github/workflows/docker.yml` file that triggers the process. Now it is set to run for every commit - I guess it is OK for testing the process, but for the long run we should create new images only upon release. Or should we maintain a "dev" version along with the released versions?

The package has its own pages at: https://github.com/pkiraly/qa-catalogue/pkgs/container/qa-catalogue

To use it:

```bash
docker pull ghcr.io/pkiraly/qa-catalogue:main
```
Please let me know your feedback!
