### ISSUE TITLE
No such container: metadata-qa-marc

### ISSUE THREAD

**Issue by Phu2** [pkiraly/qa-catalogue#453]
Run docker container:

`docker compose up -d`

then try to run analyses:

`./docker/qa-catalogue all`

results in "Error response from daemon: No such container: metadata-qa-marc".

The name of the container is hardcoded in https://github.com/pkiraly/qa-catalogue/blob/main/docker/qa-catalogue#L4

You need to set the container name in your docker compose file:

```
version: '2'

services:
  app:
    container_name: metadata-qa-marc
```

**Comment by nichtich** [comment]
Have you tried locally building the docker image? Current version from Docker hub is outdated anyway, I'm waiting for #435.

**Comment by Phu2** [comment]
> Have you tried locally building the docker image? 

Yes, i tried without success. Output from `docker compose up -d` (abridged):

```
 => CACHED [app  2/10] RUN ln -snf /usr/share/zoneinfo/Etc/UTC /etc/localtime  && echo Etc/UTC > /etc/timezone                                                                                         0.0s
 => CACHED [app  3/10] RUN apt-get update  && apt-get install -y --no-install-recommends software-properties-common gnupg2  && add-apt-repository -y ppa:openjdk-r/ppa  && echo "deb https://cloud.r-  0.0s
 => ERROR [app  4/10] COPY target/qa-catalogue-0.8.0-SNAPSHOT-release.zip /opt                                                                                                                         0.0s
------
 > [app  4/10] COPY target/qa-catalogue-0.8.0-SNAPSHOT-release.zip /opt:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref EONC:OVOA:6XTJ:JL3F:DKZK:RXOK:X5O7:6R65:T4R6:JA6L:GMB5:O2XF::ick8851rrt3yt8bohfz01id83: "/target/qa-catalogue-0.8.0-SNAPSHOT-release.zip": not found
```
Where is the SNAPSHOT supposed to come from?

`docker-compose.yml` used:
```
# Used to start the base image with `docker compose up -d`

version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./${INPUT:-input}:/opt/qa-catalogue/marc
      - ./${WEBBCONFIG:-web-config}:/var/www/html/qa-catalogue/config
    ports:
      - "${WEBPORT:-80}:80"       # qa-catalogue-web
      - "${SOLRPORT:-8983}:8983"  # Solr
```

**Comment by Phu2** [comment]
> Where is the SNAPSHOT supposed to come from?

You have to build the snapshot up front as described here https://github.com/pkiraly/qa-catalogue?tab=readme-ov-file#appendix-vi-build-docker-image

**Comment by nichtich** [comment]
Can this be closed @Phu2?
