### ISSUE TITLE
Time discrepancy in Docker

### ISSUE THREAD

**Issue by pkiraly** [pkiraly/qa-catalogue#467]
The time in the docker container is in UTC, which is 2 hours late than CET summer time, this time is displayed in the web user interface.

**Comment by Phu2** [comment]
See https://github.com/hbz/qa-catalogue/commit/5c93a40096a3c370e13553d9255bad274c408e86

**Comment by pkiraly** [comment]
@Phu2 Wouldn't you mind to create a pull request from your changes?
