### ISSUE TITLE
Docker build is broken

### ISSUE THREAD

**Issue by nichtich** [pkiraly/qa-catalogue#488]
See https://github.com/pkiraly/qa-catalogue/actions/workflows/docker.yml

**Comment by pkiraly** [comment]
The problem seems to be with the composer based installation of phpstan at the `qa-catalogue-web`:

```
- Installation request for phpstan/extension-installer 1.3.1 -> satisfiable by phpstan/extension-installer[1.3.1].
- phpstan/extension-installer 1.3.1 requires composer-plugin-api ^2.0 -> no matching package found.
```

**Comment by nichtich** [comment]
Looks like composer needs to be a newer version. Dependencies are such a beast!

**Comment by pkiraly** [comment]
I updated the base image from `ubuntu:20.04` to `ubuntu:22.04`. It solved the issue, and it means that the Docker uses PHP 8.x, instead of 7.x.
