### ISSUE TITLE
MARC 856$r mistakenly defined as obsolete

### ISSUE THREAD

**Issue by jorol** [pkiraly/qa-catalogue#541]
The MARC Avram schema <https://github.com/pkiraly/qa-catalogue/blob/main/avram-schemas/marc-schema.json> defines field 856$r as obsolete:

```
        "r": {
          "label": "Settings [OBSOLETE, 2020]",
          "deprecated": true
        },
```
The subfield was reintroduced with another definition in 2022:

```
$r - Settings [OBSOLETE, 2020]
$r - Standardized information governing use and reproduction [NEW, 2022]
```
https://www.loc.gov/marc/bibliographic/bd856.html
🤯

**Comment by pkiraly** [comment]
@jorol Thanks for calling attention to it. I'll fix it soon. BTW: it is very strange policy from the MARC21 Committee to remove it and shortly after reinstalling it with a different meaning.

**Comment by jorol** [comment]
> BTW: it is very strange policy from the MARC21 Committee to remove it and shortly after reinstalling it with a different meaning.

Yes, there will be many records with this subfield that were never adapted to the new rules...

**Comment by pkiraly** [comment]
I have updated the schema(s). The update also reflects the last two MARC updates see #544 and #545.

**Comment by jorol** [comment]
Thanks!

**Comment by jorol** [comment]
Could you please check that again? The field is still marked as deprecated in the schema files:

```
...
"r": {
"label": "Settings [OBSOLETE, 2020]",
"deprecated": true
}, 
...
```

Should be:

```
},
"r": {
"label": "Standardized information governing use and reproduction",
"repeatable": true
},
```

$r -  (R)

**Comment by pkiraly** [comment]
Sorry, there are locally defined 856s as well, and I was not careful enough. Could you check it again?

**Comment by jorol** [comment]
Looks good, thanks!
